### ISSUE TITLE
SetupSsh.ts appends known hosts multiple times

### ISSUE THREAD

**Issue by mleister97** [atymic/deployer-php-action#14]
SetupSsh.ts Line 30:

```
await fs.appendFileAsync(`${sshHome}/known_hosts`, options.knownHosts); 
```

will again and again append a line to the known hosts. Better idea would be to check if this entry already exists and only append it when it's not yet present.

Each deployment will trigger a new line addition.

**Comment by atymic** [comment]
Hmm, I thought each invocation would use a fresh container?
Feel free to PR a fix, though :)

**Comment by mleister97** [comment]
I get what you mean. However, I use the self-hosted variant instead of running directly on GitHub Servers.

**Comment by atymic** [comment]
Oh, my bad. Feel free to PR :D

**Comment by mleister97** [comment]
I also experienced a second bug on the self-hosted variant.

/tmp/ssh-auth.sock is never removed which leads to a fail in the second/third/... run as the file already exists and therefore we cannot create the file again.

Maybe I ll create a PR but I am not yet familiar with how to code a Github action.

However, great action thanks a lot

**Comment by mleister97** [comment]
Created the PR
