### ISSUE TITLE
Github deprecation warnings

### ISSUE THREAD

**Issue by tomvo** [atymic/deployer-php-action#6]
Thanks for your action!

I'm getting these deprecation warnings:

- Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

- Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Any plans to fix these or a tip on how to fix?

**Comment by jeff2013** [comment]
This is now depreciated - are there any plans to update?

**Comment by ddrager** [comment]
Yup, just got this error when trying to use this for the first time.

**Comment by atymic** [comment]
I'll fix this in the next couple of days, but happy to accept a PR if someone would like to help out as i'm pretty busy.

**Comment by atymic** [comment]
Tagged and built in https://github.com/atymic/deployer-php-action/releases/tag/0.2.0
This should solve the issue but i'll wait for confirmation before closing

**Comment by jkaan** [comment]
@atymic I was looking into what I could do to fix it, to see if I got it, the only thing left to do was to build the dist since the actions/core was updated to the latest version (which fixes the issue?)

**Comment by hbliang** [comment]
@atymic It is working now on my end!

**Comment by atymic** [comment]
Sweet, thanks!
Closing :)
